name: arrow_lang
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  fs:
  path: ^1.8.2
  universal_io: ^2.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
